name: Tests and linter
on: push
jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.6]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install poetry
          make install
      - name: Run linter
        run: |
          make lint
      - name: Run tests and collect coverage
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          URL: ${{ secrets.URL }}
        run: |
          make test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make coverage-report
          debug: true
